- name: start httdp (CentOS)
  tags: apache, centos, httpd
  service:
    name: httpd
    state: started
  when: ansible_distribution == "CentOS"
- name: install apache and php for Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name:
       - apache2
       - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for CentOS
  tags: apache,centos,http
  yum:
    name:
       - httpd
       - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (CentOS)
  tags: centos, db,mariadb
  yum:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"
- name: install mariadb package (Ubuntu)
  tags: db, mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
- name: "Mariadb - Restarting/Enabling"
  service: 
    name: mariadb
    state: restarted
    enabled: true



